### ISSUE TITLE
GCC, Pip and setuptools

### ISSUE THREAD

**Issue by acs-ferreira** [nicolargo/glancesautoinstall#16]
Any reason why not to try to autoinstall `gcc` lib on Ubuntu at [#L57](https://github.com/nicolargo/glancesautoinstall/blob/master/install.sh#L57)?

IMO, pip should also be upgraded first with `pip install --upgrade pip` at [#L90](https://github.com/nicolargo/glancesautoinstall/blob/master/install.sh#L90) _(optional)_

and then `setuptools` should be included on `$DEPS` at [#L89](https://github.com/nicolargo/glancesautoinstall/blob/master/install.sh#L89).

#my2cents

**Comment by nicolargo** [comment]
Done !

Thanks.
