### ISSUE TITLE
Install error using bitly method

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glancesautoinstall#2]
Open by @ gavinengel (Glances issue https://github.com/nicolargo/glances/issues/513)

===

Any thoughts on this? http://codepad.org/7XSooaT9

===

**Comment by gavinengel** [comment]
Thank for moving the ticket to this repo.  A bit more info on my problem.  It seems to be a problem with this:  ImportError: cannot import name unpack_url

Is the unpack_url package something I need to address on my own, or is it something your autoinstall can fix for me?

**Comment by thebwt** [comment]
> Is the unpack_url package something I need to address on my own, or is it something your autoinstall can fix for me?
That's actually a broken pip thing, and you need to reinstall pip.
