### ISSUE TITLE
MacOS X Compability

### ISSUE THREAD

**Issue by ss89** [nicolargo/glancesautoinstall#20]
Hey guys,

i would love to see OS X Compability here.
A "pip install glances" on OS X Sierra worked just fine and glances started without any visible issues to me.
If you need any information to make this work, i will be giving them to you asap.

best regards,
ss89

**Comment by nicolargo** [comment]
Hi @ss89 ,

is pip install by default ?

On my macOS Sierra 10.12.5:

    pip install glances
    pip: command not found

The GlancesAutoInstall script needs to install all the dependencies (pip and others...) before processing the Glances and libs install...

**Comment by ss89** [comment]
Hi @nicolargo,

seems you are right, it is not installed by default.
I must have installed it via brew.
The 'default' way seems to be:
- use easy_install to install pip
- use pip to install glances
Anyway, i had trouble with permissions on my old white macbook on 10.11.6.
Can you verify whether the 'default' way works for you?

**Comment by nicolargo** [comment]
I try this:

    curl -O https://bootstrap.pypa.io/get-pip.py
    sudo python get-pip.py

Ok pip is installed !

But....

   sudo pip install glances
   Error: Need 'cc' while installing PsUtil... 
   Ask to installl Xcode !!!!

**Comment by ss89** [comment]
The command line tools are 160mb in download size. 
![https___developer_apple_com_download_more_](https://user-images.githubusercontent.com/3421699/29957993-c5206e52-8ef0-11e7-865b-e3cbb4a719d2.png)

**Comment by scottcc** [comment]
Seems to work for me on multiple OSX machines here, my steps;
`brew install python` then `pip2 install glances`  (then I did `pip2 install bottle` to get the -w arg to work).

**Comment by nicolargo** [comment]
Should be done in the latest commit.

@ss89 / @scottcc Can you test it (i do not have any Mac OS X on my side)...

**Comment by ss89** [comment]
@nicolargo looks like its working for me.
I had glances installed before, so i had to:
```
pip uninstall glances
pip install glances
```

Thanks a lot!
