### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by Djabx** [nicolargo/glancesautoinstall#22]
Is there any reason why not using python3 by default (via pip3 on ubuntu) ?

**Comment by nicolargo** [comment]
Because Python 2.7 is the default Python version for Ubuntu 16.04 Long Time Support.

The glancesautoinstall script will be update for the next LTS version (Ubuntu 18.04 LTS).

**Comment by Birne94** [comment]
[zeroconf](https://github.com/jstasiak/python-zeroconf) which is used for service discovery has recently removed support for python 2. You might want to consider upgrading this script to Python 3. If I am not mistaken, python 3.5 should come preinstalled on Ubuntu 16.04.
