### ISSUE TITLE
Tokenization is happening twice

### ISSUE THREAD

**Issue by stdedos** [nicolargo/glancesautoinstall#38]
If any of the `do_with_root` argument itself contains a space, it will be re-tokenized (because of `$*`).

https://github.com/nicolargo/glancesautoinstall/blob/e2a5539523a35159b1a668458f0bc06befe15ae3/install.sh#L12-L15

You should replace all the unquoted `$*`s with `"$@"`. (NOT the `echo` one; it doesn't make sense)

It might be a good idea to shellcheck https://github.com/koalaman/shellcheck the script

**Comment by nicolargo** [comment]
Done in the latest commit.

Thanks for the issue report @stdedos
