### ISSUE TITLE
Upgrading system pip may cripple the system

### ISSUE THREAD

**Issue by stdedos** [nicolargo/glancesautoinstall#40]
At least in Ubuntu 16.04, upgrading system pip was not a very sensible action (required `sudo apt-get purge python-pip && sudo apt-get install python-pip` to recover)

https://github.com/nicolargo/glancesautoinstall/blob/e2a5539523a35159b1a668458f0bc06befe15ae3/install.sh#L137

If your only goal is to avoid having some specific broken version, it might be nice to indicate so.

**Comment by nicolargo** [comment]
Solved in last commit

**Comment by stdedos** [comment]
Duplicate of https://github.com/nicolargo/glancesautoinstall/issues/40 I guess :-D
